server:
    port: 3017
    servlet:
        session:
            timeout: PT1440M

spring:
    thymeleaf:
        cache: false
    application:
        name: web-rbac

redis:
    host: 127.0.0.1
    port: 6379
    password: 123123
    database: 2
    expire: 600

database:
    names: master
    master:
        url: jdbc:mysql://127.0.0.1/zero
        username: root
        password: 535002030102
        pool-name: master

ftp:
    domain: http://127.0.0.1:3017
    host: 127.0.0.1
    port: 21
    username: ftpUploader
    password: 123123
    bufferSize: 8096
    connectTimeOut: 10000
    readTimeOut: 10000
    basePath: /private/demo/github/mall/web.rbac/target/classes/static
    localized: true
